### ISSUE TITLE
Update BLS and pairing dependencies

### ISSUE THREAD

**Issue by eb-concordium** [Concordium/concordium-base#239]
**Task description**
Update BLS and pairing dependencies

**Comment by abizjak** [comment]
We have hit an issue in that the updated bls12 library does not expose the representation of G_t, the target group of the pairing.

We use that in one of our protocols. The options we had remaining were
- fork the library and expose the functionality. This is not good since it is a heavy maintenance burden.
- try to find some other library that would suffice. We did not manage to find anything reliable and solid. We'd have to invest significant time in either finding out, or maintaing our own fork.
- wait and ask for the functionality to be added. I have created an issue in https://github.com/zkcrypto/bls12_381/issues/96
  If that gets resolved one way or another we will have clarity on how to proceed.
